[package]
name = "chorus_studio"
version = "0.1.0"
authors = ["Daniel Hauser <daniel.hauser@liwest.at>"]

[dependencies]
gl = "0.7.0"
glutin = "0.12.0"
nalgebra = "0.13.1"
unicode-normalization = "0.1.5"

[dependencies.nanovg]
git = "https://github.com/Lisoph/nanovg-rs"
branch = "rewrite"
features = ["gl3"]