[package]
name = "chorus_studio"
version = "0.1.0"
authors = ["Daniel Hauser <daniel.hauser@liwest.at>"]

[dependencies]
gl = "0.7.0"
glutin = "0.12.0"
nalgebra = "0.13.1"
unicode-normalization = "0.1.5"
# indextree = "1.1.0"

[dependencies.nanovg]
git = "https://github.com/KevinKelley/nanovg-rs"
features = ["gl3"]

[dependencies.indextree]
git = "https://github.com/saschagrunert/indextree"