[package]
name = "chorus_studio"
version = "0.1.0"
authors = ["Daniel Hauser <daniel.hauser@liwest.at>"]

[dependencies]
glium = "0.17.1"
nalgebra = "0.12.3"
image = "0.15.0"
rusttype = "0.2.1"
unicode-normalization = "0.1.5"
unicode-segmentation = "1.2.0"