[package]
name = "server"
version = "0.1.0"
authors = ["Daniel Hauser <daniel.hauser@liwest.at>"]

[dependencies]
bincode = "1.0.1"
mio = "0.6.16"

[dependencies.proto]
path = "../proto"
version = "0.1.0"